---
  - name: Include install-git 
    include: ./common/install-git-any.yml
    
  - name: Include install-go [rpios]
    include: ./common/install-go-rpios.yml

  - name: Include install ffmpeg [any]
    include: ./sessionhost/install-ffmpeg-any.yml

  - name: Include install socat [any]
    include: ./sessionhost/install-socat-any.yml
  
  - name: Include install websocat [rpios]
    include: ./sessionhost/install-websocat-rpios.yml
    
  - name: Include stop session services [any]
    include: ./sessionhost/stop-session-services.yml
    
  - name: Include build session [rpios]
    include: ./sessionhost/build-session-rpios.yml

  - name: Include update session scripts [rpios]
    include: ./sessionhost/update-session-scripts-rpios.yml

  - name: Include update session services [any]
    include: ./sessionhost/update-session-services.yml

  - name: Include update session connections [any]
    include: ./sessionhost/update-session-connections.yml
