---
- name: update shellhost on rpi spinner v2 experiment
  hosts: rpispinnerv2
  become: yes
  gather_facts: yes
  
  tasks:

  - name: Include update-shellhost-rpios task
    include: ../tasks/update-shellhost-rpios.yml

  handlers:

  - name: Include shellhost handlers
    include: ../tasks/shellhost-handlers.yml
