---
  # untarring different versions on top of each other causes compile errors
  - name: Remove any existing go files 
    file:
      path: /usr/local/go
      state: absent
        
  - name: Download and extract golang
    ansible.builtin.unarchive:
      src: https://golang.org/dl/go1.15.7.linux-armv6l.tar.gz
      dest: /usr/local
      remote_src: yes 
